# Используем базовый образ Node.js
FROM node:18 AS build

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем package.json и package-lock.json из папки frontend-react
COPY frontend-react/package*.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем весь исходный код из папки frontend-react
COPY frontend-react .

# Создаем production build
RUN npm run build

# Используем nginx для запуска статической сборки
FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html

# Экспонируем порт для nginx
EXPOSE 80

# Запускаем nginx
CMD ["nginx", "-g", "daemon off;"]