FROM node:18

WORKDIR /app

COPY frontend-react/package*.json ./
COPY frontend-react/public ./public
COPY frontend-react/.next ./.next
COPY frontend-react/next.config.mjs ./

RUN npm install --omit=dev

EXPOSE 3000
CMD ["npm", "start"]