FROM openjdk:17-oracle
ARG JAR_FILE=backend/gateway/registration/registration-auth/build/libs/registration-auth-0.0.1-SNAPSHOT.jar
WORKDIR /opt/app
COPY ${JAR_FILE} appGateway.jar
EXPOSE 8081
ENTRYPOINT ["java","-jar","appGateway.jar"]