create database users;
create database fun_scrut;

CREATE TYPE "employment" AS ENUM (
  'SELF_EMPLOYED',
  'SCHOOL_BOY',
  'STUDENT',
  'PENSIONER',
  'UNEMPLOYED',
  'EMPLOYER',
  'EMPLOYEE',
  'OTHER'
);

CREATE TYPE "education" AS ENUM (
  'LOWER_SECONDARY',
  'SECONDARY',
  'INCOMPLETE_HIGHER',
  'HIGHER',
  'MAGISTRACY',
  'OTHER'
);

CREATE TYPE "role" AS ENUM (
  'CLIENT',
  'PARTNER',
  'ADMIN'
);

CREATE TYPE "currency" AS ENUM (
  'BYN',
  'USD',
  'EUR',
  'RUB',
  'PLN'
);

CREATE TYPE "industry" AS ENUM (
  'IT',
  'BOOKKEEPING',
  'FEC',
  'SERVICE',
  'ARMY',
  'SECURITY',
  'RAWMATERIALSMINING',
  'ART',
  'MEDECINE',
  'SCIENCE',
  'GOV_SERVICE',
  'SALES',
  'PRODUCTION',
  'BUILDING',
  'TRANSPORT',
  'OTHER'
);

CREATE TYPE "countries" AS ENUM (
  'BELARUS',
  'RUSSIA',
  'POLAND'
);

CREATE TYPE "company_legal_capacity_status" AS ENUM (
  'CAPABLE',
  'TEMPORARILY_UNAVAILABLE',
  'CLOSED'
);

CREATE TABLE "client" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "basket_id" bigint,
  "city_id" bigint,
  "activate_status" boolean,
  "birthday" date,
  "date_created" timestamp,
  "education_status" education,
  "email" varchar,
  "employment" employment,
  "first_name" varchar,
  "last_name" varchar,
  "password" varchar,
  "phone_number" varchar,
  "role" role,
  "telegram_username" varchar,
  "username" varchar
);

CREATE TABLE "partner" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "client_id" bigint
);

CREATE TABLE "country" (
  "code" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "currency" currency,
  "name" countries
);

CREATE TABLE "city" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "country_code" bigint,
  "name" varchar
);

CREATE TABLE "basket" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "total_price" varchar
);

CREATE TABLE "order" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "basket_id" bigint,
  "company_office_id" bigint,
  "position_id" bigint,
  "service_id" bigint,
  "is_expired" boolean,
  "start_work_date" timestamp,
  "total_work_days" bigint
);

CREATE TABLE "company" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "company_industry" industry,
  "legal_capacity_status" company_legal_capacity_status,
  "name" varchar,
  "site" varchar,
  "short_description" varchar
);

CREATE TABLE "review" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "company_id" bigint,
  "client_id" bigint,
  "date_created" timestamp,
  "description" varchar,
  "rate" bigint,
  "username" varchar
);

CREATE TABLE "position" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "description" varchar,
  "name" varchar
);

CREATE TABLE "service" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "price_per_day" bigint,
  "name" varchar
);

CREATE TABLE "office" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "address_id" bigint,
  "company_id" bigint,
  "phone_number" varchar
);

CREATE TABLE "address" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "city_id" bigint,
  "apartment" bigint,
  "building" bigint,
  "house" bigint,
  "street" varchar
);

CREATE TABLE "companies_positions" (
  "company_id" bigint,
  "position_id" bigint
);

ALTER TABLE "client" ADD FOREIGN KEY ("city_id") REFERENCES "city" ("id");

ALTER TABLE "client" ADD FOREIGN KEY ("basket_id") REFERENCES "basket" ("id");

ALTER TABLE "city" ADD FOREIGN KEY ("country_code") REFERENCES "country" ("code");

ALTER TABLE "companies_positions" ADD FOREIGN KEY ("company_id") REFERENCES "company" ("id");

ALTER TABLE "companies_positions" ADD FOREIGN KEY ("position_id") REFERENCES "position" ("id");

ALTER TABLE "order" ADD FOREIGN KEY ("position_id") REFERENCES "position" ("id");

ALTER TABLE "order" ADD FOREIGN KEY ("basket_id") REFERENCES "basket" ("id");

ALTER TABLE "order" ADD FOREIGN KEY ("company_office_id") REFERENCES "office" ("id");

ALTER TABLE "order" ADD FOREIGN KEY ("service_id") REFERENCES "service" ("id");

CREATE TABLE "company_partner" (
  "company_id" bigint,
  "partner_id" bigint,
  PRIMARY KEY ("company_id", "partner_id")
);

ALTER TABLE "company_partner" ADD FOREIGN KEY ("company_id") REFERENCES "company" ("id");

ALTER TABLE "company_partner" ADD FOREIGN KEY ("partner_id") REFERENCES "partner" ("id");


ALTER TABLE "address" ADD FOREIGN KEY ("city_id") REFERENCES "city" ("id");

ALTER TABLE "office" ADD FOREIGN KEY ("company_id") REFERENCES "company" ("id");

ALTER TABLE "office" ADD FOREIGN KEY ("address_id") REFERENCES "address" ("id");

ALTER TABLE "review" ADD FOREIGN KEY ("company_id") REFERENCES "company" ("id");

ALTER TABLE "partner" ADD FOREIGN KEY ("client_id") REFERENCES "client" ("id");

ALTER TABLE "review" ADD FOREIGN KEY ("client_id") REFERENCES "client" ("id");