interface ICompanyContent {
    companyName: string
    industry: string
    image: string
    price: number
    id: number
}

export const content: ICompanyContent[] = [
    {
        companyName: 'EPAM Systems',
        industry: 'IT-отрасль',
        image: '/images/epam_for_companies_page.png',
        price: 120,
        id: 1,
    },
    {
        companyName: 'EPAM Systems',
        industry: 'IT-отрасль',
        image: '/images/epam_for_companies_page.png',
        price: 125,
        id: 2,
    },
    {
        companyName: 'EPAM Systems',
        industry: 'IT-отрасль',
        image: '/images/epam_for_companies_page.png',
        price: 130,
        id: 3,
    },
    {
        companyName: 'EPAM Systems',
        industry: 'IT-отрасль',
        image: '/images/epam_for_companies_page.png',
        price: 110,
        id: 4,
    },
    {
        companyName: 'EPAM Systems',
        industry: 'IT-отрасль',
        image: '/images/epam_for_companies_page.png',
        price: 140,
        id: 5,
    },
    {
        companyName: 'EPAM Systems',
        industry: 'IT-отрасль',
        image: '/images/epam_for_companies_page.png',
        price: 135,
        id: 6,
    },
    {
        companyName: 'EPAM Systems',
        industry: 'IT-отрасль',
        image: '/images/epam_for_companies_page.png',
        price: 128,
        id: 7,
    },
    {
        companyName: 'EPAM Systems',
        industry: 'IT-отрасль',
        image: '/images/epam_for_companies_page.png',
        price: 122,
        id: 8,
    },
    {
        companyName: 'EPAM Systems',
        industry: 'IT-отрасль',
        image: '/images/epam_for_companies_page.png',
        price: 127,
        id: 9,
    },
    {
        companyName: 'EPAM Systems',
        industry: 'IT-отрасль',
        image: '/images/epam_for_companies_page.png',
        price: 133,
        id: 10,
    },
    {
        companyName: 'EPAM Systems',
        industry: 'IT-отрасль',
        image: '/images/epam_for_companies_page.png',
        price: 138,
        id: 11,
    },
    {
        companyName: 'EPAM Systems',
        industry: 'IT-отрасль',
        image: '/images/epam_for_companies_page.png',
        price: 129,
        id: 12,
    },

    {
        companyName: 'Наименование компании',
        industry: 'Здравоохранение',
        image: '/images/profession_1.jpg',
        price: 100,
        id: 13,
    },
    {
        companyName: 'Наименование компании',
        industry: 'Здравоохранение',
        image: '/images/profession_1.jpg',
        price: 105,
        id: 14,
    },
    {
        companyName: 'Наименование компании',
        industry: 'Здравоохранение',
        image: '/images/profession_1.jpg',
        price: 95,
        id: 15,
    },
    {
        companyName: 'Наименование компании',
        industry: 'Здравоохранение',
        image: '/images/profession_1.jpg',
        price: 102,
        id: 16,
    },
    {
        companyName: 'Наименование компании',
        industry: 'Здравоохранение',
        image: '/images/profession_1.jpg',
        price: 98,
        id: 17,
    },
    {
        companyName: 'Наименование компании',
        industry: 'Здравоохранение',
        image: '/images/profession_1.jpg',
        price: 106,
        id: 18,
    },

    {
        companyName: 'Наименование компании',
        industry: 'Искусство',
        image: '/images/profession_2.jpg',
        price: 80,
        id: 19,
    },
    {
        companyName: 'Наименование компании',
        industry: 'Искусство',
        image: '/images/profession_2.jpg',
        price: 85,
        id: 20,
    },
    {
        companyName: 'Наименование компании',
        industry: 'Искусство',
        image: '/images/profession_2.jpg',
        price: 75,
        id: 21,
    },
    {
        companyName: 'Наименование компании',
        industry: 'Искусство',
        image: '/images/profession_2.jpg',
        price: 88,
        id: 22,
    },
    {
        companyName: 'Наименование компании',
        industry: 'Искусство',
        image: '/images/profession_2.jpg',
        price: 82,
        id: 23,
    },
    {
        companyName: 'Наименование компании',
        industry: 'Искусство',
        image: '/images/profession_2.jpg',
        price: 86,
        id: 24,
    },
    {
        companyName: 'Наименование компании',
        industry: 'Искусство',
        image: '/images/profession_2.jpg',
        price: 90,
        id: 25,
    },
    {
        companyName: 'Наименование компании',
        industry: 'Искусство',
        image: '/images/profession_2.jpg',
        price: 87,
        id: 26,
    },
    {
        companyName: 'Наименование компании',
        industry: 'Искусство',
        image: '/images/profession_2.jpg',
        price: 84,
        id: 27,
    },

    { companyName: 'Наименование компании', industry: 'Спорт', image: '/images/profession_3.jpg', price: 92, id: 28 },
    { companyName: 'Наименование компании', industry: 'Спорт', image: '/images/profession_3.jpg', price: 95, id: 29 },
    { companyName: 'Наименование компании', industry: 'Спорт', image: '/images/profession_3.jpg', price: 90, id: 30 },
    { companyName: 'Наименование компании', industry: 'Спорт', image: '/images/profession_3.jpg', price: 94, id: 31 },
    { companyName: 'Наименование компании', industry: 'Спорт', image: '/images/profession_3.jpg', price: 89, id: 32 },
    { companyName: 'Наименование компании', industry: 'Спорт', image: '/images/profession_3.jpg', price: 91, id: 33 },
    { companyName: 'Наименование компании', industry: 'Спорт', image: '/images/profession_3.jpg', price: 93, id: 34 },
    { companyName: 'Наименование компании', industry: 'Спорт', image: '/images/profession_3.jpg', price: 97, id: 35 },
    { companyName: 'Наименование компании', industry: 'Спорт', image: '/images/profession_3.jpg', price: 96, id: 36 },
]
