function getInDaysISO(days: number): string {
    const d = new Date()
    d.setDate(d.getDate() + days)
    return d.toISOString().slice(0, 10)
}
function getTodayISO(): string {
    return getInDaysISO(0)
}
function getTomorrowISO(): string {
    return getInDaysISO(1)
}
function getThisWeekISO(): string {
    return getInDaysISO(3)
}
function getThisMonthISO(): string {
    return getInDaysISO(10)
}
function getInNext3MonthsISO(): string {
    return getInDaysISO(40)
}

export interface IEventApiContent {
    id: string
    date: string
    description: string
    name: string
    publicPlaceName: string
    site: string
    price: string
    city: {
        id: string
        name: string
    }
    time: string
    organizer: string
    eventCategory: {
        id: string
        category: string
    }
}

export const fakeEvents: IEventApiContent[] = [
    {
        id: '1',
        date: getTodayISO(),
        description: 'IT выставка о современных технологиях и инновациях.',
        name: 'Tech Expo 2025',
        publicPlaceName: 'Технопарк Минск',
        site: 'https://techexpominsk.by',
        price: 'Бесплатно',
        city: { id: '1', name: 'Минск' },
        time: '10:00',
        organizer: 'IT Belarus',
        eventCategory: { id: '1', category: 'Выставка/презентация' },
    },
    {
        id: '2',
        date: getThisMonthISO(),
        description: 'Ведущая конференция по искусственному интеллекту и data science.',
        name: 'AI Future Conference',
        publicPlaceName: 'Дворец искусств',
        site: 'https://aifuture.by',
        price: '25 BYN',
        city: { id: '2', name: 'Гомель' },
        time: '11:00',
        organizer: 'Gomel Tech Club',
        eventCategory: { id: '2', category: 'Конференция' },
    },
    {
        id: '3',
        date: getThisMonthISO(),
        description: 'Семинар для начинающих разработчиков: React & Next.js.',
        name: 'Frontend Boost',
        publicPlaceName: 'IT-центр Могилёв',
        site: 'https://frontendboost.by',
        price: '15 BYN',
        city: { id: '3', name: 'Могилёв' },
        time: '12:30',
        organizer: 'Mogilev Devs',
        eventCategory: { id: '3', category: 'Мастер-класс/семинар/тренинг' },
    },
    {
        id: '4',
        date: getTomorrowISO(),
        description: 'День открытых дверей: офис EPAM Systems.',
        name: 'Open IT Day',
        publicPlaceName: 'EPAM офис, Витебск',
        site: 'https://openitday.by',
        price: 'Бесплатно',
        city: { id: '4', name: 'Витебск' },
        time: '10:00',
        organizer: 'EPAM',
        eventCategory: { id: '5', category: 'День открытых дверей' },
    },
    {
        id: '5',
        date: getThisMonthISO(),
        description: 'Стажировка для студентов: Python backend.',
        name: 'Python Internship',
        publicPlaceName: 'Гродно Айти Хаб',
        site: 'https://internshippython.by',
        price: 'Бесплатно (отбор по резюме)',
        city: { id: '5', name: 'Гродно' },
        time: '09:30',
        organizer: 'Grodno IT Hub',
        eventCategory: { id: '4', category: 'Стажировка' },
    },
    {
        id: '6',
        date: getTomorrowISO(),
        description: 'Ярмарка вакансий для разработчиков и тестировщиков.',
        name: 'IT Job Fair 2025',
        publicPlaceName: 'Брест Конференц Центр',
        site: 'https://itjobfair.by',
        price: 'Бесплатно',
        city: { id: '6', name: 'Брест' },
        time: '13:00',
        organizer: 'HR IT Group',
        eventCategory: { id: '6', category: 'Ярмарка вакансий' },
    },
    {
        id: '7',
        date: getInNext3MonthsISO(),
        description: 'Тренинг: управление проектами для junior IT специалистов.',
        name: 'Project Management Basics',
        publicPlaceName: 'IT-Академия, Барановичи',
        site: 'https://pmtrain.by',
        price: '10 BYN',
        city: { id: '7', name: 'Барановичи' },
        time: '16:00',
        organizer: 'IT-Академия',
        eventCategory: { id: '3', category: 'Мастер-класс/семинар/тренинг' },
    },
    {
        id: '8',
        date: getInDaysISO(40),
        description: 'День открытых дверей в стартап-инкубаторе.',
        name: 'Startup Day',
        publicPlaceName: 'Startup Hub, Бобруйск',
        site: 'https://startupday.by',
        price: 'Бесплатно',
        city: { id: '8', name: 'Бобруйск' },
        time: '14:00',
        organizer: 'Startup Hub',
        eventCategory: { id: '5', category: 'День открытых дверей' },
    },
    {
        id: '9',
        date: getThisWeekISO(),
        description: 'Презентация новых IT-решений от лидеров рынка.',
        name: 'Digital Solutions Expo',
        publicPlaceName: 'Борисов Digital Hall',
        site: 'https://digitalexpo.by',
        price: '20 BYN',
        city: { id: '9', name: 'Борисов' },
        time: '10:00',
        organizer: 'Digital Belarus',
        eventCategory: { id: '1', category: 'Выставка/презентация' },
    },
    {
        id: '10',
        date: getInDaysISO(17),
        description: 'Воркшоп по созданию мобильных приложений с Flutter.',
        name: 'Flutter Mobile Camp',
        publicPlaceName: 'Tech Loft Минск',
        site: 'https://fluttercamp.by',
        price: '30 BYN',
        city: { id: '1', name: 'Минск' },
        time: '10:30',
        organizer: 'FlutterBY',
        eventCategory: { id: '3', category: 'Мастер-класс/семинар/тренинг' },
    },
    {
        id: '11',
        date: getTomorrowISO(),
        description: 'Открытый митап о новых трендах кибербезопасности.',
        name: 'CyberSecurity Meetup',
        publicPlaceName: 'IT-Кластер, Брест',
        site: 'https://cybermeet.by',
        price: 'Бесплатно',
        city: { id: '6', name: 'Брест' },
        time: '18:00',
        organizer: 'Brest Tech Space',
        eventCategory: { id: '2', category: 'Конференция' },
    },
    {
        id: '12',
        date: getInNext3MonthsISO(),
        description: 'День карьеры для студентов и выпускников IT-специальностей.',
        name: 'IT Career Day',
        publicPlaceName: 'Университет ИТ, Минск',
        site: 'https://itcareerday.by',
        price: 'Бесплатно',
        city: { id: '1', name: 'Минск' },
        time: '09:00',
        organizer: 'IT Belarus',
        eventCategory: { id: '6', category: 'Ярмарка вакансий' },
    },
    {
        id: '13',
        date: getThisWeekISO(),
        description: 'Семинар: автоматизация тестирования и QA-практики.',
        name: 'QA Automation Workshop',
        publicPlaceName: 'QA Hub Гомель',
        site: 'https://qaworkshop.by',
        price: '20 BYN',
        city: { id: '2', name: 'Гомель' },
        time: '13:00',
        organizer: 'Gomel QA Club',
        eventCategory: { id: '3', category: 'Мастер-класс/семинар/тренинг' },
    },
    {
        id: '14',
        date: getThisMonthISO(),
        description: 'Интенсив по веб-дизайну и UX/UI для начинающих.',
        name: 'Web Design Starter',
        publicPlaceName: 'Digital Studio Могилёв',
        site: 'https://webdesign.by',
        price: '10 BYN',
        city: { id: '3', name: 'Могилёв' },
        time: '15:30',
        organizer: 'Mogilev Devs',
        eventCategory: { id: '3', category: 'Мастер-класс/семинар/тренинг' },
    },
    {
        id: '15',
        date: getInDaysISO(12),
        description: 'Презентация стартапов и проектов в сфере HealthTech.',
        name: 'HealthTech Pitch Day',
        publicPlaceName: 'Startup Hub, Бобруйск',
        site: 'https://healthtech.by',
        price: 'Бесплатно',
        city: { id: '8', name: 'Бобруйск' },
        time: '11:00',
        organizer: 'Startup Hub',
        eventCategory: { id: '1', category: 'Выставка/презентация' },
    },
    {
        id: '16',
        date: getInDaysISO(5),
        description: 'Стажировка по Data Science: практика с реальными данными.',
        name: 'Data Science Internship',
        publicPlaceName: 'DataLab, Витебск',
        site: 'https://dsintern.by',
        price: 'Бесплатно (отбор по тестовому заданию)',
        city: { id: '4', name: 'Витебск' },
        time: '10:00',
        organizer: 'DataLab Vitebsk',
        eventCategory: { id: '4', category: 'Стажировка' },
    },
    {
        id: '17',
        date: getTomorrowISO(),
        description: 'День открытых дверей: Digital агентство “WebWizards”.',
        name: 'Web Agency Open Day',
        publicPlaceName: 'WebWizards офис, Гродно',
        site: 'https://webwizards.by',
        price: 'Бесплатно',
        city: { id: '5', name: 'Гродно' },
        time: '10:00',
        organizer: 'WebWizards',
        eventCategory: { id: '5', category: 'День открытых дверей' },
    },
    {
        id: '18',
        date: getThisMonthISO(),
        description: 'Региональный IT-хакатон для разработчиков и дизайнеров.',
        name: 'Regional IT Hackathon',
        publicPlaceName: 'Innovation Center, Барановичи',
        site: 'https://ithackathon.by',
        price: 'Бесплатно (по регистрации)',
        city: { id: '7', name: 'Барановичи' },
        time: '09:00',
        organizer: 'IT-Академия',
        eventCategory: { id: '2', category: 'Конференция' },
    },
    {
        id: '19',
        date: getInDaysISO(30),
        description: 'Фестиваль современных цифровых технологий и искусственного интеллекта.',
        name: 'Digital Future Fest',
        publicPlaceName: 'Digital Arena, Борисов',
        site: 'https://digitalfuture.by',
        price: '25 BYN',
        city: { id: '9', name: 'Борисов' },
        time: '17:00',
        organizer: 'Digital Belarus',
        eventCategory: { id: '1', category: 'Выставка/презентация' },
    },

    {
        id: '20',
        date: getInDaysISO(14),
        description: 'Hackathon: Решение бизнес-задач с помощью ИИ.',
        name: 'AI Hackathon',
        publicPlaceName: 'Smart Hall, Минск',
        site: 'https://aihacks.by',
        price: 'Бесплатно (регистрация)',
        city: { id: '1', name: 'Минск' },
        time: '09:30',
        organizer: 'AI Minsk',
        eventCategory: { id: '2', category: 'Конференция' },
    },
    {
        id: '21',
        date: getThisMonthISO(),
        description: 'Летний лагерь по разработке игр на Unity.',
        name: 'Unity Game Camp',
        publicPlaceName: 'GameDev Park, Витебск',
        site: 'https://unitycamp.by',
        price: '30 BYN',
        city: { id: '4', name: 'Витебск' },
        time: '12:00',
        organizer: 'GameDev Vitebsk',
        eventCategory: { id: '3', category: 'Мастер-класс/семинар/тренинг' },
    },
    {
        id: '22',
        date: getInNext3MonthsISO(),
        description: 'Демо-день студенческих проектов.',
        name: 'Student Demo Day',
        publicPlaceName: 'University Hall, Гомель',
        site: 'https://studemo.by',
        price: 'Бесплатно',
        city: { id: '2', name: 'Гомель' },
        time: '15:00',
        organizer: 'Gomel Tech Club',
        eventCategory: { id: '1', category: 'Выставка/презентация' },
    },
    {
        id: '23',
        date: getInDaysISO(8),
        description: 'Мастер-класс по UX-исследованиям.',
        name: 'UX Research Masterclass',
        publicPlaceName: 'Design Center, Могилёв',
        site: 'https://uxresearch.by',
        price: '12 BYN',
        city: { id: '3', name: 'Могилёв' },
        time: '11:00',
        organizer: 'Mogilev Devs',
        eventCategory: { id: '3', category: 'Мастер-класс/семинар/тренинг' },
    },
    {
        id: '24',
        date: getTomorrowISO(),
        description: 'Воркшоп по кибербезопасности.',
        name: 'Cybersecurity Bootcamp',
        publicPlaceName: 'Security Lab, Брест',
        site: 'https://cyberbootcamp.by',
        price: 'Бесплатно',
        city: { id: '6', name: 'Брест' },
        time: '16:00',
        organizer: 'Brest Tech Space',
        eventCategory: { id: '3', category: 'Мастер-класс/семинар/тренинг' },
    },
    {
        id: '25',
        date: getThisWeekISO(),
        description: 'Ярмарка IT стартапов.',
        name: 'IT Startup Fair',
        publicPlaceName: 'Innovation Center, Барановичи',
        site: 'https://itstartupfair.by',
        price: 'Бесплатно',
        city: { id: '7', name: 'Барановичи' },
        time: '14:30',
        organizer: 'Startup Hub',
        eventCategory: { id: '1', category: 'Выставка/презентация' },
    },
    {
        id: '26',
        date: getInDaysISO(25),
        description: 'День карьеры для дизайнеров и маркетологов.',
        name: 'Creative Career Day',
        publicPlaceName: 'Art Hall, Гродно',
        site: 'https://creativecareer.by',
        price: 'Бесплатно',
        city: { id: '5', name: 'Гродно' },
        time: '13:00',
        organizer: 'Grodno Art Hub',
        eventCategory: { id: '6', category: 'Ярмарка вакансий' },
    },
    {
        id: '27',
        date: getTodayISO(),
        description: 'Открытая лекция: Интернет вещей в Беларуси.',
        name: 'IoT in Belarus',
        publicPlaceName: 'Tech Loft, Минск',
        site: 'https://iotminsk.by',
        price: '10 BYN',
        city: { id: '1', name: 'Минск' },
        time: '17:00',
        organizer: 'IoT Belarus',
        eventCategory: { id: '2', category: 'Конференция' },
    },
    {
        id: '28',
        date: getInDaysISO(6),
        description: 'Встреча выпускников IT-академии.',
        name: 'Alumni IT Meetup',
        publicPlaceName: 'IT-Академия, Барановичи',
        site: 'https://alumniit.by',
        price: 'Бесплатно',
        city: { id: '7', name: 'Барановичи' },
        time: '18:30',
        organizer: 'IT-Академия',
        eventCategory: { id: '2', category: 'Конференция' },
    },
    {
        id: '29',
        date: getInDaysISO(20),
        description: 'Семинар: Docker и микросервисы.',
        name: 'Docker Microservices Workshop',
        publicPlaceName: 'Dev Center, Борисов',
        site: 'https://dockermicro.by',
        price: '15 BYN',
        city: { id: '9', name: 'Борисов' },
        time: '11:00',
        organizer: 'Digital Belarus',
        eventCategory: { id: '3', category: 'Мастер-класс/семинар/тренинг' },
    },
    {
        id: '30',
        date: getThisWeekISO(),
        description: 'Экспо VR-технологий для образования.',
        name: 'VR Edu Expo',
        publicPlaceName: 'Education Hub, Гомель',
        site: 'https://vreduexpo.by',
        price: '25 BYN',
        city: { id: '2', name: 'Гомель' },
        time: '10:00',
        organizer: 'Gomel Tech Club',
        eventCategory: { id: '1', category: 'Выставка/презентация' },
    },
    {
        id: '31',
        date: getThisMonthISO(),
        description: 'Стажировка для студентов по Java.',
        name: 'Java Student Internship',
        publicPlaceName: 'Java Center, Могилёв',
        site: 'https://javaintern.by',
        price: 'Бесплатно',
        city: { id: '3', name: 'Могилёв' },
        time: '09:00',
        organizer: 'Mogilev Devs',
        eventCategory: { id: '4', category: 'Стажировка' },
    },
    {
        id: '32',
        date: getInDaysISO(27),
        description: 'День открытых дверей в дизайн-студии.',
        name: 'Design Open Day',
        publicPlaceName: 'Digital Studio, Гомель',
        site: 'https://designopenday.by',
        price: 'Бесплатно',
        city: { id: '2', name: 'Гомель' },
        time: '15:00',
        organizer: 'Digital Studio',
        eventCategory: { id: '5', category: 'День открытых дверей' },
    },
    {
        id: '33',
        date: getInDaysISO(23),
        description: 'Летний лагерь по робототехнике.',
        name: 'Robotics Summer Camp',
        publicPlaceName: 'Robotics Lab, Брест',
        site: 'https://roboticscamp.by',
        price: '20 BYN',
        city: { id: '6', name: 'Брест' },
        time: '11:30',
        organizer: 'Brest Tech Space',
        eventCategory: { id: '3', category: 'Мастер-класс/семинар/тренинг' },
    },
    {
        id: '34',
        date: getInNext3MonthsISO(),
        description: 'Демо-день стартапов в Борисове.',
        name: 'Borisov Startup Demo Day',
        publicPlaceName: 'Startup Hub, Борисов',
        site: 'https://borisovstartup.by',
        price: 'Бесплатно',
        city: { id: '9', name: 'Борисов' },
        time: '16:00',
        organizer: 'Digital Belarus',
        eventCategory: { id: '1', category: 'Выставка/презентация' },
    },
    {
        id: '35',
        date: getInDaysISO(16),
        description: 'Воркшоп: автоматизация бизнеса с помощью CRM.',
        name: 'CRM Business Automation',
        publicPlaceName: 'CRM Hub, Могилёв',
        site: 'https://crmhub.by',
        price: '15 BYN',
        city: { id: '3', name: 'Могилёв' },
        time: '13:00',
        organizer: 'Mogilev Devs',
        eventCategory: { id: '3', category: 'Мастер-класс/семинар/тренинг' },
    },
    {
        id: '36',
        date: getTodayISO(),
        description: 'Онлайн-митап: будущее фриланса в IT.',
        name: 'Freelance Future',
        publicPlaceName: 'Online',
        site: 'https://freelancefuture.by',
        price: 'Бесплатно',
        city: { id: '1', name: 'Минск' },
        time: '19:00',
        organizer: 'IT Belarus',
        eventCategory: { id: '2', category: 'Конференция' },
    },
]
