server:
  port: 8585
  error:
    include-stacktrace: never

spring:
  application:
    name: ru-file-transfer
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  web:
    cors:
      allowed-origins: "*"
      allowed-methods: "*"
      
logging:
  charset:
    console: UTF-8