interface IContent {
    profession: string
    category: string
    image: string
    price: number
    id: number
    internshipType: string
}

export const content: IContent[] = [
    {
        profession: 'Программист',
        image: '/images/profession_1.jpg',
        price: 30,
        id: 1,
        category: 'IT-отрасль',
        internshipType: 'Участник',
    },
    {
        profession: 'Программист',
        image: '/images/profession_2.jpg',
        price: 40,
        id: 2,
        category: 'IT-отрасль',
        internshipType: 'Наблюдатель',
    },
    {
        profession: 'Программист',
        image: '/images/profession_3.jpg',
        price: 35,
        id: 3,
        category: 'IT-отрасль',
        internshipType: 'Наблюдатель',
    },
    {
        profession: 'Программист',
        image: '/images/profession_4.jpg',
        price: 50,
        id: 4,
        category: 'IT-отрасль',
        internshipType: 'Наблюдатель',
    },
    {
        profession: 'Программист',
        image: '/images/profession_2.jpg',
        price: 45,
        id: 5,
        category: 'IT-отрасль',
        internshipType: 'Наблюдатель',
    },
    {
        profession: 'Программист',
        image: '/images/profession_3.jpg',
        price: 55,
        id: 6,
        category: 'IT-отрасль',
        internshipType: 'Наблюдатель',
    },
    {
        profession: 'Программист',
        image: '/images/profession_1.jpg',
        price: 60,
        id: 7,
        category: 'IT-отрасль',
        internshipType: 'Наблюдатель',
    },
    {
        profession: 'Программист',
        image: '/images/profession_4.jpg',
        price: 50,
        id: 8,
        category: 'IT-отрасль',
        internshipType: 'Наблюдатель',
    },
    {
        profession: 'Программист',
        image: '/images/profession_2.jpg',
        price: 40,
        id: 9,
        category: 'IT-отрасль',
        internshipType: 'Участник',
    },
    {
        profession: 'Программист',
        image: '/images/profession_3.jpg',
        price: 35,
        id: 10,
        category: 'IT-отрасль',
        internshipType: 'Участник',
    },
    {
        profession: 'Программист',
        image: '/images/profession_4.jpg',
        price: 50,
        id: 11,
        category: 'IT-отрасль',
        internshipType: 'Участник',
    },
    {
        profession: 'Бизнес-аналитик, программист',
        image: '/images/profession_2.jpg',
        price: 40,
        id: 12,
        category: 'IT-отрасль',
        internshipType: 'Наблюдатель',
    },

    {
        profession: 'Медсестра',
        image: '/images/profession_4.jpg',
        price: 30,
        id: 13,
        category: 'Здравоохранение',
        internshipType: 'Наблюдатель',
    },
    {
        profession: 'Хирург',
        image: '/images/profession_1.jpg',
        price: 100,
        id: 14,
        category: 'Здравоохранение',
        internshipType: 'Наблюдатель',
    },
    {
        profession: 'Педиатр',
        image: '/images/profession_2.jpg',
        price: 60,
        id: 15,
        category: 'Здравоохранение',
        internshipType: 'Участник',
    },
    {
        profession: 'Офтальмолог',
        image: '/images/profession_3.jpg',
        price: 50,
        id: 16,
        category: 'Здравоохранение',
        internshipType: 'Участник',
    },
    {
        profession: 'Диетолог',
        image: '/images/profession_4.jpg',
        price: 45,
        id: 17,
        category: 'Здравоохранение',
        internshipType: 'Участник',
    },
    {
        profession: 'Кардиолог',
        image: '/images/profession_1.jpg',
        price: 90,
        id: 18,
        category: 'Здравоохранение',
        internshipType: 'Наблюдатель',
    },

    {
        profession: 'Художник',
        image: '/images/profession_2.jpg',
        price: 40,
        id: 19,
        category: 'Искусство',
        internshipType: 'Участник',
    },
    {
        profession: 'Графический дизайнер',
        image: '/images/profession_3.jpg',
        price: 50,
        id: 20,
        category: 'Искусство',
        internshipType: 'Наблюдатель',
    },
    {
        profession: 'Музыкант',
        image: '/images/profession_1.jpg',
        price: 35,
        id: 21,
        category: 'Искусство',
        internshipType: 'Участник',
    },
    {
        profession: 'Актёр',
        image: '/images/profession_4.jpg',
        price: 70,
        id: 22,
        category: 'Искусство',
        internshipType: 'Наблюдатель',
    },
    {
        profession: 'Фотограф',
        image: '/images/profession_2.jpg',
        price: 45,
        id: 23,
        category: 'Искусство',
        internshipType: 'Участник',
    },
    {
        profession: 'Скульптор',
        image: '/images/profession_3.jpg',
        price: 60,
        id: 24,
        category: 'Искусство',
        internshipType: 'Наблюдатель',
    },
    {
        profession: 'Режиссёр',
        image: '/images/profession_1.jpg',
        price: 90,
        id: 25,
        category: 'Искусство',
        internshipType: 'Наблюдатель',
    },
    {
        profession: 'Продюсер',
        image: '/images/profession_4.jpg',
        price: 80,
        id: 26,
        category: 'Искусство',
        internshipType: 'Участник',
    },
    {
        profession: 'Писатель',
        image: '/images/profession_2.jpg',
        price: 50,
        id: 27,
        category: 'Искусство',
        internshipType: 'Наблюдатель',
    },

    {
        profession: 'Тренер по фитнесу',
        image: '/images/profession_3.jpg',
        price: 40,
        id: 28,
        category: 'Спорт',
        internshipType: 'Наблюдатель',
    },
    {
        profession: 'Футболист',
        image: '/images/profession_1.jpg',
        price: 70,
        id: 29,
        category: 'Спорт',
        internshipType: 'Участник',
    },
    {
        profession: 'Баскетболист',
        image: '/images/profession_2.jpg',
        price: 60,
        id: 30,
        category: 'Спорт',
        internshipType: 'Наблюдатель',
    },
    {
        profession: 'Теннисист',
        image: '/images/profession_4.jpg',
        price: 80,
        id: 31,
        category: 'Спорт',
        internshipType: 'Участник',
    },
    {
        profession: 'Лыжник',
        image: '/images/profession_3.jpg',
        price: 45,
        id: 32,
        category: 'Спорт',
        internshipType: 'Наблюдатель',
    },
    {
        profession: 'Бегун',
        image: '/images/profession_1.jpg',
        price: 35,
        id: 33,
        category: 'Спорт',
        internshipType: 'Участник',
    },
    {
        profession: 'Тренер по плаванию',
        image: '/images/profession_4.jpg',
        price: 50,
        id: 34,
        category: 'Спорт',
        internshipType: 'Наблюдатель',
    },
    {
        profession: 'Боксер',
        image: '/images/profession_2.jpg',
        price: 60,
        id: 35,
        category: 'Спорт',
        internshipType: 'Участник',
    },
    {
        profession: 'Йога-инструктор',
        image: '/images/profession_3.jpg',
        price: 40,
        id: 36,
        category: 'Спорт',
        internshipType: 'Наблюдатель',
    },
]
